name:                solar-schedule
version:             0.1.0.0
github:              "ptrchas3/solar-schedule"
license:             BSD3
author:              "Peter Chase"
maintainer:          "peter.chase@ptrchas3.com"
copyright:           "2021 Peter Chase"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ptrchas3/solar-schedule#readme>

dependencies:
- base >= 4.7 && < 5
- time >= 1.12 && < 2

library:
  source-dirs: src

executables:
  solar-schedule-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solar-schedule

tests:
  solar-schedule-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solar-schedule
